version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    groups:
      event-calendar:
        patterns:
          - '@event-calendar/*'
      development-dependencies:
        dependency-type: 'development'
        exclude-patterns:
          - '@event-calendar/*'
      production-dependencies:
        dependency-type: 'production'
        exclude-patterns:
          - '@event-calendar/*'
